import React from 'react';

const Enquirenow = () => {
  return (
    <div>
      <div
        style={{
          margin: 0,
          blockSize: '587.273px',
          borderBlockEndColor: 'rgb(33, 37, 41)',
          borderBlockStartColor: 'rgb(33, 37, 41)',
          borderBottomColor: 'rgb(33, 37, 41)',
          borderInlineEndColor: 'rgb(33, 37, 41)',
          borderInlineStartColor: 'rgb(33, 37, 41)',
          borderLeftColor: 'rgb(33, 37, 41)',
          borderRightColor: 'rgb(33, 37, 41)',
          borderTopColor: 'rgb(33, 37, 41)',
          boxSizing: 'border-box',
          caretColor: 'rgb(33, 37, 41)',
          color: 'rgb(33, 37, 41)',
          columnRuleColor: 'rgb(33, 37, 41)',
          fontFamily: 'Manrope',
          fontSize: '16px',
          inlineSize: '1353.75px',
          lineHeight: '24px',
          outlineColor: 'rgb(33, 37, 41)',
          paddingBlockStart: '50px',
          paddingInlineEnd: '12px',
          paddingInlineStart: '12px',
          paddingLeft: '12px',
          paddingRight: '12px',
          paddingTop: '50px',
          textDecoration: 'none solid rgb(33, 37, 41)',
          textDecorationColor: 'rgb(33, 37, 41)',
          textEmphasisColor: 'rgb(33, 37, 41)',
          textSizeAdjust: '100%',
          WebkitTapHighlightColor: 'rgba(0, 0, 0, 0)',
          WebkitTextFillColor: 'rgb(33, 37, 41)',
          WebkitTextStrokeColor: 'rgb(33, 37, 41)',
          width: '1353.75px',
          height: '587.273px',
        }}
        className={'container-fluid commoncontainer'}
      >
        <div
          style={{
            blockSize: '107.094px',
            borderBlockEndColor: 'rgb(33, 37, 41)',
            borderBlockStartColor: 'rgb(33, 37, 41)',
            borderBottomColor: 'rgb(33, 37, 41)',
            borderInlineEndColor: 'rgb(33, 37, 41)',
            borderInlineStartColor: 'rgb(33, 37, 41)',
            borderLeftColor: 'rgb(33, 37, 41)',
            borderRightColor: 'rgb(33, 37, 41)',
            borderTopColor: 'rgb(33, 37, 41)',
            boxSizing: 'border-box',
            caretColor: 'rgb(33, 37, 41)',
            color: 'rgb(33, 37, 41)',
            columnRuleColor: 'rgb(33, 37, 41)',
            display: 'flex',
            flexWrap: 'wrap',
            fontFamily: 'Manrope',
            fontSize: '16px',
            inlineSize: '1353.75px',
            lineHeight: '24px',
            marginInlineEnd: '-12px',
            marginInlineStart: '-12px',
            marginLeft: 'calc(var(--bs-gutter-x) * -0.5)',
            marginRight: 'calc(var(--bs-gutter-x) * -0.5)',
            marginTop: 'calc(var(--bs-gutter-y) * -1)',
            outlineColor: 'rgb(33, 37, 41)',
            textDecoration: 'none solid rgb(33, 37, 41)',
            textDecorationColor: 'rgb(33, 37, 41)',
            textEmphasisColor: 'rgb(33, 37, 41)',
            textSizeAdjust: '100%',
            WebkitTapHighlightColor: 'rgba(0, 0, 0, 0)',
            WebkitTextFillColor: 'rgb(33, 37, 41)',
            WebkitTextStrokeColor: 'rgb(33, 37, 41)',
          }}
          className={'row'}
        >
          <div
            style={{
              blockSize: '107.094px',
              borderBlockEndColor: 'rgb(33, 37, 41)',
              borderBlockStartColor: 'rgb(33, 37, 41)',
              borderBottomColor: 'rgb(33, 37, 41)',
              borderInlineEndColor: 'rgb(33, 37, 41)',
              borderInlineStartColor: 'rgb(33, 37, 41)',
              borderLeftColor: 'rgb(33, 37, 41)',
              borderRightColor: 'rgb(33, 37, 41)',
              borderTopColor: 'rgb(33, 37, 41)',
              boxSizing: 'border-box',
              caretColor: 'rgb(33, 37, 41)',
              color: 'rgb(33, 37, 41)',
              columnRuleColor: 'rgb(33, 37, 41)',
              flexShrink: 0,
              fontFamily: 'Manrope',
              fontSize: '16px',
              inlineSize: '1353.75px',
              lineHeight: '24px',
              marginLeft: 0,
              marginRight: 0,
              maxInlineSize: '100%',
              maxWidth: '100%',
              minBlockSize: 'auto',
              minHeight: 'auto',
              minInlineSize: 'auto',
              minWidth: 'auto',
              outlineColor: 'rgb(33, 37, 41)',
              paddingInlineEnd: '12px',
              paddingInlineStart: '12px',
              paddingLeft: '12px',
              paddingRight: '12px',
              textDecoration: 'none solid rgb(33, 37, 41)',
              textDecorationColor: 'rgb(33, 37, 41)',
              textEmphasisColor: 'rgb(33, 37, 41)',
              textSizeAdjust: '100%',
              WebkitTapHighlightColor: 'rgba(0, 0, 0, 0)',
              WebkitTextFillColor: 'rgb(33, 37, 41)',
              WebkitTextStrokeColor: 'rgb(33, 37, 41)',
              width: '100%',
            }}
            className={'col-md-12'}
          >
            <div
              style={{
                blockSize: '33.5938px',
                borderBlockEndColor: 'rgb(33, 37, 41)',
                borderBlockStartColor: 'rgb(33, 37, 41)',
                borderBottomColor: 'rgb(33, 37, 41)',
                borderInlineEndColor: 'rgb(33, 37, 41)',
                borderInlineStartColor: '#ff5733',
                borderInlineStartStyle: 'solid',
                borderInlineStartWidth: '4px',
                borderLeftColor: '#ff5733',
                borderLeftStyle: 'solid',
                borderLeftWidth: '4px',
                borderRightColor: 'rgb(33, 37, 41)',
                borderTopColor: 'rgb(33, 37, 41)',
                boxSizing: 'border-box',
                caretColor: 'rgb(33, 37, 41)',
                color: 'rgb(33, 37, 41)',
                columnRuleColor: 'rgb(33, 37, 41)',
                fontFamily: 'Manrope',
                fontSize: '16px',
                inlineSize: '1329.75px',
                lineHeight: '24px',
                marginLeft: 0,
                marginRight: 0,
                outlineColor: 'rgb(33, 37, 41)',
                textDecoration: 'none solid rgb(33, 37, 41)',
                textDecorationColor: 'rgb(33, 37, 41)',
                textEmphasisColor: 'rgb(33, 37, 41)',
                textSizeAdjust: '100%',
                WebkitTapHighlightColor: 'rgba(0, 0, 0, 0)',
                WebkitTextFillColor: 'rgb(33, 37, 41)',
                WebkitTextStrokeColor: 'rgb(33, 37, 41)',
              }}
              className={'vl'}
            >
              <div
                style={{
                  blockSize: '33.5938px',
                  borderBlockEndColor: 'rgb(33, 37, 41)',
                  borderBlockStartColor: 'rgb(33, 37, 41)',
                  borderBottomColor: 'rgb(33, 37, 41)',
                  borderInlineEndColor: 'rgb(33, 37, 41)',
                  borderInlineStartColor: 'rgb(33, 37, 41)',
                  borderLeftColor: 'rgb(33, 37, 41)',
                  borderRightColor: 'rgb(33, 37, 41)',
                  borderTopColor: 'rgb(33, 37, 41)',
                  boxSizing: 'border-box',
                  caretColor: 'rgb(33, 37, 41)',
                  color: 'rgb(33, 37, 41)',
                  columnRuleColor: 'rgb(33, 37, 41)',
                  fontFamily: 'Manrope',
                  fontSize: '16px',
                  inlineSize: '1325.75px',
                  lineHeight: '24px',
                  marginLeft: 0,
                  marginRight: 0,
                  outlineColor: 'rgb(33, 37, 41)',
                  paddingInlineStart: '15px',
                  paddingLeft: '15px',
                  textDecoration: 'none solid rgb(33, 37, 41)',
                  textDecorationColor: 'rgb(33, 37, 41)',
                  textEmphasisColor: 'rgb(33, 37, 41)',
                  textSizeAdjust: '100%',
                  WebkitTapHighlightColor: 'rgba(0, 0, 0, 0)',
                  WebkitTextFillColor: 'rgb(33, 37, 41)',
                  WebkitTextStrokeColor: 'rgb(33, 37, 41)',
                }}
                className={'vltext'}
              >
                <h3
                  style={{
                    blockSize: '33.5938px',
                    borderBlockEndColor: 'rgb(255, 255, 255)',
                    borderBlockStartColor: 'rgb(255, 255, 255)',
                    borderBottomColor: 'rgb(255, 255, 255)',
                    borderInlineEndColor: 'rgb(255, 255, 255)',
                    borderInlineStartColor: 'rgb(255, 255, 255)',
                    borderLeftColor: 'rgb(255, 255, 255)',
                    borderRightColor: 'rgb(255, 255, 255)',
                    borderTopColor: 'rgb(255, 255, 255)',
                    boxSizing: 'border-box',
                    caretColor: 'rgb(255, 255, 255)',
                    color: 'rgb(255, 255, 255)',
                    columnRuleColor: 'rgb(255, 255, 255)',
                    fontFamily: 'Playfair Display',
                    fontSize: '28px',
                    fontWeight: 500,
                    inlineSize: '1310.75px',
                    lineHeight: '33.6px',
                    marginBlockEnd: '8px',
                    marginBlockStart: '0px',
                    marginBottom: '0.5rem',
                    marginLeft: 0,
                    marginRight: 0,
                    marginTop: '0px',
                    outlineColor: 'rgb(255, 255, 255)',
                    textDecoration: 'none solid rgb(255, 255, 255)',
                    textDecorationColor: 'rgb(255, 255, 255)',
                    textEmphasisColor: 'rgb(255, 255, 255)',
                    textSizeAdjust: '100%',
                    WebkitTapHighlightColor: 'rgba(0, 0, 0, 0)',
                    WebkitTextFillColor: 'rgb(255, 255, 255)',
                    WebkitTextStrokeColor: 'rgb(255, 255, 255)',
                  }}
                  className={'colorwhite'}
                >
                  {' '}
                  Enquire Now
                </h3>
              </div>
            </div>
            <div
              style={{
                blockSize: '25.5px',
                borderBlockEndColor: 'rgb(33, 37, 41)',
                borderBlockStartColor: 'rgb(33, 37, 41)',
                borderBottomColor: 'rgb(33, 37, 41)',
                borderInlineEndColor: 'rgb(33, 37, 41)',
                borderInlineStartColor: 'rgb(33, 37, 41)',
                borderLeftColor: 'rgb(33, 37, 41)',
                borderRightColor: 'rgb(33, 37, 41)',
                borderTopColor: 'rgb(33, 37, 41)',
                boxSizing: 'border-box',
                caretColor: 'rgb(33, 37, 41)',
                color: 'rgb(33, 37, 41)',
                columnRuleColor: 'rgb(33, 37, 41)',
                fontFamily: 'Manrope',
                fontSize: '16px',
                inlineSize: '1329.75px',
                lineHeight: '24px',
                marginLeft: 0,
                marginRight: 0,
                outlineColor: 'rgb(33, 37, 41)',
                paddingInlineStart: '20px',
                paddingLeft: '20px',
                textDecoration: 'none solid rgb(33, 37, 41)',
                textDecorationColor: 'rgb(33, 37, 41)',
                textEmphasisColor: 'rgb(33, 37, 41)',
                textSizeAdjust: '100%',
                WebkitTapHighlightColor: 'rgba(0, 0, 0, 0)',
                WebkitTextFillColor: 'rgb(33, 37, 41)',
                WebkitTextStrokeColor: 'rgb(33, 37, 41)',
              }}
              className={'leftdiv'}
            >
              <p
                style={{
                  blockSize: '25.5px',
                  borderBlockEndColor: '#ff5733',
                  borderBlockStartColor: '#ff5733',
                  borderBottomColor: '#ff5733',
                  borderInlineEndColor: '#ff5733',
                  borderInlineStartColor: '#ff5733',
                  borderLeftColor: '#ff5733',
                  borderRightColor: '#ff5733',
                  borderTopColor: '#ff5733',
                  boxSizing: 'border-box',
                  caretColor: '#ff5733',
                  color: '#ff5733',
                  columnRuleColor: '#ff5733',
                  fontFamily: 'Manrope',
                  fontSize: '17px',
                  inlineSize: '1309.75px',
                  lineHeight: '25.5px',
                  marginBlockStart: '0px',
                  marginBottom: '1rem',
                  marginLeft: 0,
                  marginRight: 0,
                  marginTop: '0px',
                  outlineColor: '#ff5733',
                  textDecoration: 'none solid #ff5733',
                  textDecorationColor: '#ff5733',
                  textEmphasisColor: '#ff5733',
                  textSizeAdjust: '100%',
                  WebkitTapHighlightColor: 'rgba(0, 0, 0, 0)',
                  WebkitTextFillColor: '#ff5733',
                  WebkitTextStrokeColor: '#ff5733',
                }}
                className={'colorgreen'}
              >
                We would love to hear from you!
              </p>
            </div>
            <br
              style={{
                borderBlockEndColor: 'rgb(33, 37, 41)',
                borderBlockStartColor: 'rgb(33, 37, 41)',
                borderBottomColor: 'rgb(33, 37, 41)',
                borderInlineEndColor: 'rgb(33, 37, 41)',
                borderInlineStartColor: 'rgb(33, 37, 41)',
                borderLeftColor: 'rgb(33, 37, 41)',
                borderRightColor: 'rgb(33, 37, 41)',
                borderTopColor: 'rgb(33, 37, 41)',
                boxSizing: 'border-box',
                caretColor: 'rgb(33, 37, 41)',
                color: 'rgb(33, 37, 41)',
                columnRuleColor: 'rgb(33, 37, 41)',
                fontFamily: 'Manrope',
                fontSize: '16px',
                lineHeight: '24px',
                marginLeft: 0,
                marginRight: 0,
                outlineColor: 'rgb(33, 37, 41)',
                textDecoration: 'none solid rgb(33, 37, 41)',
                textDecorationColor: 'rgb(33, 37, 41)',
                textEmphasisColor: 'rgb(33, 37, 41)',
                textSizeAdjust: '100%',
                WebkitTapHighlightColor: 'rgba(0, 0, 0, 0)',
                WebkitTextFillColor: 'rgb(33, 37, 41)',
                WebkitTextStrokeColor: 'rgb(33, 37, 41)',
              }}
            />
          </div>
        </div>
        <div
          style={{
            alignItems: 'center',
            blockSize: '430.18px',
            borderBlockEndColor: 'rgb(33, 37, 41)',
            borderBlockStartColor: 'rgb(33, 37, 41)',
            borderBottomColor: 'rgb(33, 37, 41)',
            borderInlineEndColor: 'rgb(33, 37, 41)',
            borderInlineStartColor: 'rgb(33, 37, 41)',
            borderLeftColor: 'rgb(33, 37, 41)',
            borderRightColor: 'rgb(33, 37, 41)',
            borderTopColor: 'rgb(33, 37, 41)',
            boxSizing: 'border-box',
            caretColor: 'rgb(33, 37, 41)',
            color: 'rgb(33, 37, 41)',
            columnRuleColor: 'rgb(33, 37, 41)',
            display: 'flex',
            flexWrap: 'wrap',
            fontFamily: 'Manrope',
            fontSize: '16px',
            inlineSize: '1353.75px',
            lineHeight: '24px',
            marginInlineEnd: '-12px',
            marginInlineStart: '-12px',
            marginLeft: 'calc(var(--bs-gutter-x) * -0.5)',
            marginRight: 'calc(var(--bs-gutter-x) * -0.5)',
            marginTop: 'calc(var(--bs-gutter-y) * -1)',
            outlineColor: 'rgb(33, 37, 41)',
            paddingInlineStart: '20px',
            paddingLeft: '20px',
            textDecoration: 'none solid rgb(33, 37, 41)',
            textDecorationColor: 'rgb(33, 37, 41)',
            textEmphasisColor: 'rgb(33, 37, 41)',
            textSizeAdjust: '100%',
            WebkitTapHighlightColor: 'rgba(0, 0, 0, 0)',
            WebkitTextFillColor: 'rgb(33, 37, 41)',
            WebkitTextStrokeColor: 'rgb(33, 37, 41)',
          }}
          className={'row align-items-center leftdiv'}
        >
          <div
            style={{
              blockSize: '406.18px',
              borderBlockEndColor: 'rgb(33, 37, 41)',
              borderBlockStartColor: 'rgb(33, 37, 41)',
              borderBottomColor: 'rgb(33, 37, 41)',
              borderInlineEndColor: 'rgb(33, 37, 41)',
              borderInlineStartColor: 'rgb(33, 37, 41)',
              borderLeftColor: 'rgb(33, 37, 41)',
              borderRightColor: 'rgb(33, 37, 41)',
              borderTopColor: 'rgb(33, 37, 41)',
              boxSizing: 'border-box',
              caretColor: 'rgb(33, 37, 41)',
              color: 'rgb(33, 37, 41)',
              columnRuleColor: 'rgb(33, 37, 41)',
              flexShrink: 0,
              fontFamily: 'Manrope',
              fontSize: '16px',
              inlineSize: '666.875px',
              lineHeight: '24px',
              marginBlockEnd: '24px',
              marginBottom: '1.5rem !important',
              marginLeft: 0,
              marginRight: 0,
              maxInlineSize: '100%',
              maxWidth: '100%',
              minBlockSize: 'auto',
              minHeight: 'auto',
              minInlineSize: 'auto',
              minWidth: 'auto',
              outlineColor: 'rgb(33, 37, 41)',
              paddingInlineEnd: '12px',
              paddingInlineStart: '12px',
              paddingLeft: '12px',
              paddingRight: '12px',
              textDecoration: 'none solid rgb(33, 37, 41)',
              textDecorationColor: 'rgb(33, 37, 41)',
              textEmphasisColor: 'rgb(33, 37, 41)',
              textSizeAdjust: '100%',
              WebkitTapHighlightColor: 'rgba(0, 0, 0, 0)',
              WebkitTextFillColor: 'rgb(33, 37, 41)',
              WebkitTextStrokeColor: 'rgb(33, 37, 41)',
              width: '666.875px',
              height: '406.18px',
            }}
            className={'col-md-6 mb-4'}
          >
            <img
              style={{
                blockSize: '406.18px',
                borderBlockEndColor: 'rgb(33, 37, 41)',
                borderBlockStartColor: 'rgb(33, 37, 41)',
                borderBottomColor: 'rgb(33, 37, 41)',
                borderInlineEndColor: 'rgb(33, 37, 41)',
                borderInlineStartColor: 'rgb(33, 37, 41)',
                borderLeftColor: 'rgb(33, 37, 41)',
                borderRightColor: 'rgb(33, 37, 41)',
                borderTopColor: 'rgb(33, 37, 41)',
                boxSizing: 'border-box',
                caretColor: 'rgb(33, 37, 41)',
                color: 'rgb(33, 37, 41)',
                columnRuleColor: 'rgb(33, 37, 41)',
                fontFamily: 'Manrope',
                fontSize: '16px',
                inlineSize: '642.875px',
                lineHeight: '24px',
                marginLeft: 0,
                marginRight: 0,
                outlineColor: 'rgb(33, 37, 41)',
                textDecoration: 'none solid rgb(33, 37, 41)',
                textDecorationColor: 'rgb(33, 37, 41)',
                textEmphasisColor: 'rgb(33, 37, 41)',
                textSizeAdjust: '100%',
                verticalAlign: 'middle',
                WebkitTapHighlightColor: 'rgba(0, 0, 0, 0)',
                WebkitTextFillColor: 'rgb(33, 37, 41)',
                WebkitTextStrokeColor: 'rgb(33, 37, 41)',
                width: '100%',
                height: '406.18px',
              }}
              src={'http://www.qyk.energy/assets/img/enquireimg.jpg'}
              className={'enquireimg'}
              alt="enquireimg"
            ></img>
          </div>
          <div
            style={{
              blockSize: '382px',
              borderBlockEndColor: 'rgb(33, 37, 41)',
              borderBlockStartColor: 'rgb(33, 37, 41)',
              borderBottomColor: 'rgb(33, 37, 41)',
              borderInlineEndColor: 'rgb(33, 37, 41)',
              borderInlineStartColor: 'rgb(33, 37, 41)',
              borderLeftColor: 'rgb(33, 37, 41)',
              borderRightColor: 'rgb(33, 37, 41)',
              borderTopColor: 'rgb(33, 37, 41)',
              boxSizing: 'border-box',
              caretColor: 'rgb(33, 37, 41)',
              color: 'rgb(33, 37, 41)',
              columnRuleColor: 'rgb(33, 37, 41)',
              flexShrink: 0,
              fontFamily: 'Manrope',
              fontSize: '16px',
              inlineSize: '666.875px',
              lineHeight: '24px',
              marginBlockEnd: '24px',
              marginBottom: '1.5rem !important',
              marginLeft: 0,
              marginRight: 0,
              maxInlineSize: '100%',
              maxWidth: '100%',
              minBlockSize: 'auto',
              minHeight: 'auto',
              minInlineSize: 'auto',
              minWidth: 'auto',
              outlineColor: 'rgb(33, 37, 41)',
              paddingInlineEnd: '12px',
              paddingInlineStart: '12px',
              paddingLeft: '12px',
              paddingRight: '12px',
              textDecoration: 'none solid rgb(33, 37, 41)',
              textDecorationColor: 'rgb(33, 37, 41)',
              textEmphasisColor: 'rgb(33, 37, 41)',
              textSizeAdjust: '100%',
              WebkitTapHighlightColor: 'rgba(0, 0, 0, 0)',
              WebkitTextFillColor: 'rgb(33, 37, 41)',
              WebkitTextStrokeColor: 'rgb(33, 37, 41)',
              width: '666.875px',
            }}
            className={'col-md-6 mb-4'}
          >
            <div
              style={{
                blockSize: '382px',
                borderBlockEndColor: 'rgba(255, 255, 255, 0.7)',
                borderBlockEndStyle: 'solid',
                borderBlockEndWidth: '1px',
                borderBlockStartColor: 'rgba(255, 255, 255, 0.7)',
                borderBlockStartStyle: 'solid',
                borderBlockStartWidth: '1px',
                borderBottomColor: 'rgba(255, 255, 255, 0.7)',
                borderBottomStyle: 'solid',
                borderBottomWidth: '1px',
                borderInlineEndColor: 'rgba(255, 255, 255, 0.7)',
                borderInlineEndStyle: 'solid',
                borderInlineEndWidth: '1px',
                borderInlineStartColor: 'rgba(255, 255, 255, 0.7)',
                borderInlineStartStyle: 'solid',
                borderInlineStartWidth: '1px',
                borderLeftColor: 'rgba(255, 255, 255, 0.7)',
                borderLeftStyle: 'solid',
                borderLeftWidth: '1px',
                borderRightColor: 'rgba(255, 255, 255, 0.7)',
                borderRightStyle: 'solid',
                borderRightWidth: '1px',
                borderTopColor: 'rgba(255, 255, 255, 0.7)',
                borderTopStyle: 'solid',
                borderTopWidth: '1px',
                boxSizing: 'border-box',
                caretColor: 'rgb(33, 37, 41)',
                color: 'rgb(33, 37, 41)',
                columnRuleColor: 'rgb(33, 37, 41)',
                fontFamily: 'Manrope',
                fontSize: '16px',
                inlineSize: '642.875px',
                lineHeight: '24px',
                marginLeft: 0,
                marginRight: 0,
                outlineColor: 'rgb(33, 37, 41)',
                paddingBlockEnd: '20px',
                paddingBlockStart: '20px',
                paddingBottom: '20px',
                paddingInlineEnd: '20px',
                paddingInlineStart: '20px',
                paddingLeft: '20px',
                paddingRight: '20px',
                paddingTop: '20px',
                textDecoration: 'none solid rgb(33, 37, 41)',
                textDecorationColor: 'rgb(33, 37, 41)',
                textEmphasisColor: 'rgb(33, 37, 41)',
                textSizeAdjust: '100%',
                WebkitTapHighlightColor: 'rgba(0, 0, 0, 0)',
                WebkitTextFillColor: 'rgb(33, 37, 41)',
                WebkitTextStrokeColor: 'rgb(33, 37, 41)',
              }}
              className={'formcard'}
            >
              <form
                style={{
                  blockSize: '340px',
                  borderBlockEndColor: 'rgb(33, 37, 41)',
                  borderBlockStartColor: 'rgb(33, 37, 41)',
                  borderBottomColor: 'rgb(33, 37, 41)',
                  borderInlineEndColor: 'rgb(33, 37, 41)',
                  borderInlineStartColor: 'rgb(33, 37, 41)',
                  borderLeftColor: 'rgb(33, 37, 41)',
                  borderRightColor: 'rgb(33, 37, 41)',
                  borderTopColor: 'rgb(33, 37, 41)',
                  boxSizing: 'border-box',
                  caretColor: 'rgb(33, 37, 41)',
                  color: 'rgb(33, 37, 41)',
                  columnRuleColor: 'rgb(33, 37, 41)',
                  fontFamily: 'Manrope',
                  fontSize: '16px',
                  inlineSize: '600.875px',
                  lineHeight: '24px',
                  marginBlockEnd: '0px',
                  marginBottom: '0px',
                  marginLeft: 0,
                  marginRight: 0,
                  outlineColor: 'rgb(33, 37, 41)',
                  textDecoration: 'none solid rgb(33, 37, 41)',
                  textDecorationColor: 'rgb(33, 37, 41)',
                  textEmphasisColor: 'rgb(33, 37, 41)',
                  textSizeAdjust: '100%',
                  WebkitTapHighlightColor: 'rgba(0, 0, 0, 0)',
                  WebkitTextFillColor: 'rgb(33, 37, 41)',
                  WebkitTextStrokeColor: 'rgb(33, 37, 41)',
                }}
                method={'POST'}
                action={'#'}
                id={'enquiry-form'}
              >
                <div
                  style={{
                    blockSize: '48px',
                    borderBlockEndColor: 'rgb(33, 37, 41)',
                    borderBlockStartColor: 'rgb(33, 37, 41)',
                    borderBottomColor: 'rgb(33, 37, 41)',
                    borderInlineEndColor: 'rgb(33, 37, 41)',
                    borderInlineStartColor: 'rgb(33, 37, 41)',
                    borderLeftColor: 'rgb(33, 37, 41)',
                    borderRightColor: 'rgb(33, 37, 41)',
                    borderTopColor: 'rgb(33, 37, 41)',
                    boxSizing: 'border-box',
                    caretColor: 'rgb(33, 37, 41)',
                    color: 'rgb(33, 37, 41)',
                    columnRuleColor: 'rgb(33, 37, 41)',
                    fontFamily: 'Manrope',
                    fontSize: '16px',
                    inlineSize: '600.875px',
                    lineHeight: '24px',
                    marginBlockEnd: '16px',
                    marginBottom: '1rem !important',
                    marginLeft: 0,
                    marginRight: 0,
                    outlineColor: 'rgb(33, 37, 41)',
                    textDecoration: 'none solid rgb(33, 37, 41)',
                    textDecorationColor: 'rgb(33, 37, 41)',
                    textEmphasisColor: 'rgb(33, 37, 41)',
                    textSizeAdjust: '100%',
                    WebkitTapHighlightColor: 'rgba(0, 0, 0, 0)',
                    WebkitTextFillColor: 'rgb(33, 37, 41)',
                    WebkitTextStrokeColor: 'rgb(33, 37, 41)',
                  }}
                  className={'mb-3'}
                >
                  <input
                    style={{
                      appearance: 'none',
                      backgroundClip: 'padding-box',
                      backgroundColor: 'rgba(0, 0, 0, 0)',
                      blockSize: '48px',
                      borderBlockEndColor: 'rgb(206, 212, 218)',
                      borderBlockEndStyle: 'solid',
                      borderBlockEndWidth: '1px',
                      borderBlockStartColor: 'rgb(206, 212, 218)',
                      borderBlockStartStyle: 'solid',
                      borderBlockStartWidth: '1px',
                      borderBottomColor: 'rgb(206, 212, 218)',
                      borderBottomStyle: 'solid',
                      borderBottomWidth: '1px',
                      borderInlineEndColor: 'rgb(206, 212, 218)',
                      borderInlineEndStyle: 'solid',
                      borderInlineEndWidth: '1px',
                      borderInlineStartColor: 'rgb(206, 212, 218)',
                      borderInlineStartStyle: 'solid',
                      borderInlineStartWidth: '1px',
                      borderLeftColor: 'rgb(206, 212, 218)',
                      borderLeftStyle: 'solid',
                      borderLeftWidth: '1px',
                      borderRightColor: 'rgb(206, 212, 218)',
                      borderRightStyle: 'solid',
                      borderRightWidth: '1px',
                      borderTopColor: 'rgb(206, 212, 218)',
                      borderTopStyle: 'solid',
                      borderTopWidth: '1px',
                      boxSizing: 'border-box',
                      caretColor: 'rgb(255, 255, 255)',
                      color: 'rgb(255, 255, 255)',
                      columnRuleColor: 'rgb(255, 255, 255)',
                      display: 'block',
                      fontFamily: 'Manrope',
                      fontSize: '16px',
                      inlineSize: '600.875px',
                      lineHeight: '24px',
                      marginLeft: 0,
                      marginRight: 0,
                      outlineColor: 'rgb(255, 255, 255)',
                      paddingBlockEnd: '6px',
                      paddingBlockStart: '6px',
                      paddingBottom: '6px',
                      paddingInlineEnd: '12px',
                      paddingInlineStart: '12px',
                      paddingLeft: '12px',
                      paddingRight: '12px',
                      paddingTop: '6px',
                      textDecoration: 'none solid rgb(255, 255, 255)',
                      textDecorationColor: 'rgb(255, 255, 255)',
                      textEmphasisColor: 'rgb(255, 255, 255)',
                      textSizeAdjust: '100%',
                      transitionDelay: '0s, 0s',
                      transitionDuration: '0.15s, 0.15s',
                      transitionProperty: 'border-color, box-shadow',
                      transitionTimingFunction: 'ease-in-out, ease-in-out',
                      WebkitTapHighlightColor: 'rgba(0, 0, 0, 0)',
                      WebkitTextFillColor: 'rgb(255, 255, 255)',
                      WebkitTextStrokeColor: 'rgb(255, 255, 255)',
                      width: '100%',
                      height: '48px',
                    }}
                    type={'text'}
                    className={'form-control forminput'}
                    placeholder={'Name'}
                  ></input>
                </div>
                <div
                  style={{
                    blockSize: '48px',
                    borderBlockEndColor: 'rgb(33, 37, 41)',
                    borderBlockStartColor: 'rgb(33, 37, 41)',
                    borderBottomColor: 'rgb(33, 37, 41)',
                    borderInlineEndColor: 'rgb(33, 37, 41)',
                    borderInlineStartColor: 'rgb(33, 37, 41)',
                    borderLeftColor: 'rgb(33, 37, 41)',
                    borderRightColor: 'rgb(33, 37, 41)',
                    borderTopColor: 'rgb(33, 37, 41)',
                    boxSizing: 'border-box',
                    caretColor: 'rgb(33, 37, 41)',
                    color: 'rgb(33, 37, 41)',
                    columnRuleColor: 'rgb(33, 37, 41)',
                    fontFamily: 'Manrope',
                    fontSize: '16px',
                    inlineSize: '600.875px',
                    lineHeight: '24px',
                    marginBlockEnd: '16px',
                    marginBottom: '1rem !important',
                    marginLeft: 0,
                    marginRight: 0,
                    outlineColor: 'rgb(33, 37, 41)',
                    textDecoration: 'none solid rgb(33, 37, 41)',
                    textDecorationColor: 'rgb(33, 37, 41)',
                    textEmphasisColor: 'rgb(33, 37, 41)',
                    textSizeAdjust: '100%',
                    WebkitTapHighlightColor: 'rgba(0, 0, 0, 0)',
                    WebkitTextFillColor: 'rgb(33, 37, 41)',
                    WebkitTextStrokeColor: 'rgb(33, 37, 41)',
                  }}
                  className={'mb-3'}
                >
                  <input
                    style={{
                      appearance: 'none',
                      backgroundClip: 'padding-box',
                      backgroundColor: 'rgba(0, 0, 0, 0)',
                      blockSize: '48px',
                      borderBlockEndColor: 'rgb(206, 212, 218)',
                      borderBlockEndStyle: 'solid',
                      borderBlockEndWidth: '1px',
                      borderBlockStartColor: 'rgb(206, 212, 218)',
                      borderBlockStartStyle: 'solid',
                      borderBlockStartWidth: '1px',
                      borderBottomColor: 'rgb(206, 212, 218)',
                      borderBottomStyle: 'solid',
                      borderBottomWidth: '1px',
                      borderInlineEndColor: 'rgb(206, 212, 218)',
                      borderInlineEndStyle: 'solid',
                      borderInlineEndWidth: '1px',
                      borderInlineStartColor: 'rgb(206, 212, 218)',
                      borderInlineStartStyle: 'solid',
                      borderInlineStartWidth: '1px',
                      borderLeftColor: 'rgb(206, 212, 218)',
                      borderLeftStyle: 'solid',
                      borderLeftWidth: '1px',
                      borderRightColor: 'rgb(206, 212, 218)',
                      borderRightStyle: 'solid',
                      borderRightWidth: '1px',
                      borderTopColor: 'rgb(206, 212, 218)',
                      borderTopStyle: 'solid',
                      borderTopWidth: '1px',
                      boxSizing: 'border-box',
                      caretColor: 'rgb(255, 255, 255)',
                      color: 'rgb(255, 255, 255)',
                      columnRuleColor: 'rgb(255, 255, 255)',
                      display: 'block',
                      fontFamily: 'Manrope',
                      fontSize: '16px',
                      inlineSize: '600.875px',
                      lineHeight: '24px',
                      marginLeft: 0,
                      marginRight: 0,
                      outlineColor: 'rgb(255, 255, 255)',
                      paddingBlockEnd: '6px',
                      paddingBlockStart: '6px',
                      paddingBottom: '6px',
                      paddingInlineEnd: '12px',
                      paddingInlineStart: '12px',
                      paddingLeft: '12px',
                      paddingRight: '12px',
                      paddingTop: '6px',
                      textDecoration: 'none solid rgb(255, 255, 255)',
                      textDecorationColor: 'rgb(255, 255, 255)',
                      textEmphasisColor: 'rgb(255, 255, 255)',
                      textSizeAdjust: '100%',
                      transitionDelay: '0s, 0s',
                      transitionDuration: '0.15s, 0.15s',
                      transitionProperty: 'border-color, box-shadow',
                      transitionTimingFunction: 'ease-in-out, ease-in-out',
                      WebkitTapHighlightColor: 'rgba(0, 0, 0, 0)',
                      WebkitTextFillColor: 'rgb(255, 255, 255)',
                      WebkitTextStrokeColor: 'rgb(255, 255, 255)',
                      width: '100%',
                      height: '48px',
                    }}
                    type={'email'}
                    className={'form-control forminput'}
                    placeholder={'Email'}
                  ></input>
                </div>
                <div
                  style={{
                    blockSize: '48px',
                    borderBlockEndColor: 'rgb(33, 37, 41)',
                    borderBlockStartColor: 'rgb(33, 37, 41)',
                    borderBottomColor: 'rgb(33, 37, 41)',
                    borderInlineEndColor: 'rgb(33, 37, 41)',
                    borderInlineStartColor: 'rgb(33, 37, 41)',
                    borderLeftColor: 'rgb(33, 37, 41)',
                    borderRightColor: 'rgb(33, 37, 41)',
                    borderTopColor: 'rgb(33, 37, 41)',
                    boxSizing: 'border-box',
                    caretColor: 'rgb(33, 37, 41)',
                    color: 'rgb(33, 37, 41)',
                    columnRuleColor: 'rgb(33, 37, 41)',
                    fontFamily: 'Manrope',
                    fontSize: '16px',
                    inlineSize: '600.875px',
                    lineHeight: '24px',
                    marginBlockEnd: '16px',
                    marginBottom: '1rem !important',
                    marginLeft: 0,
                    marginRight: 0,
                    outlineColor: 'rgb(33, 37, 41)',
                    textDecoration: 'none solid rgb(33, 37, 41)',
                    textDecorationColor: 'rgb(33, 37, 41)',
                    textEmphasisColor: 'rgb(33, 37, 41)',
                    textSizeAdjust: '100%',
                    WebkitTapHighlightColor: 'rgba(0, 0, 0, 0)',
                    WebkitTextFillColor: 'rgb(33, 37, 41)',
                    WebkitTextStrokeColor: 'rgb(33, 37, 41)',
                  }}
                  className={'mb-3'}
                >
                  <input
                    style={{
                      appearance: 'none',
                      backgroundClip: 'padding-box',
                      backgroundColor: 'rgba(0, 0, 0, 0)',
                      blockSize: '48px',
                      borderBlockEndColor: 'rgb(206, 212, 218)',
                      borderBlockEndStyle: 'solid',
                      borderBlockEndWidth: '1px',
                      borderBlockStartColor: 'rgb(206, 212, 218)',
                      borderBlockStartStyle: 'solid',
                      borderBlockStartWidth: '1px',
                      borderBottomColor: 'rgb(206, 212, 218)',
                      borderBottomStyle: 'solid',
                      borderBottomWidth: '1px',
                      borderInlineEndColor: 'rgb(206, 212, 218)',
                      borderInlineEndStyle: 'solid',
                      borderInlineEndWidth: '1px',
                      borderInlineStartColor: 'rgb(206, 212, 218)',
                      borderInlineStartStyle: 'solid',
                      borderInlineStartWidth: '1px',
                      borderLeftColor: 'rgb(206, 212, 218)',
                      borderLeftStyle: 'solid',
                      borderLeftWidth: '1px',
                      borderRightColor: 'rgb(206, 212, 218)',
                      borderRightStyle: 'solid',
                      borderRightWidth: '1px',
                      borderTopColor: 'rgb(206, 212, 218)',
                      borderTopStyle: 'solid',
                      borderTopWidth: '1px',
                      boxSizing: 'border-box',
                      caretColor: 'rgb(255, 255, 255)',
                      color: 'rgb(255, 255, 255)',
                      columnRuleColor: 'rgb(255, 255, 255)',
                      display: 'block',
                      fontFamily: 'Manrope',
                      fontSize: '16px',
                      inlineSize: '600.875px',
                      lineHeight: '24px',
                      marginLeft: 0,
                      marginRight: 0,
                      outlineColor: 'rgb(255, 255, 255)',
                      paddingBlockEnd: '6px',
                      paddingBlockStart: '6px',
                      paddingBottom: '6px',
                      paddingInlineEnd: '12px',
                      paddingInlineStart: '12px',
                      paddingLeft: '12px',
                      paddingRight: '12px',
                      paddingTop: '6px',
                      textDecoration: 'none solid rgb(255, 255, 255)',
                      textDecorationColor: 'rgb(255, 255, 255)',
                      textEmphasisColor: 'rgb(255, 255, 255)',
                      textSizeAdjust: '100%',
                      transitionDelay: '0s, 0s',
                      transitionDuration: '0.15s, 0.15s',
                      transitionProperty: 'border-color, box-shadow',
                      transitionTimingFunction: 'ease-in-out, ease-in-out',
                      WebkitTapHighlightColor: 'rgba(0, 0, 0, 0)',
                      WebkitTextFillColor: 'rgb(255, 255, 255)',
                      WebkitTextStrokeColor: 'rgb(255, 255, 255)',
                      width: '100%',
                      height: '48px',
                    }}
                    type={'text'}
                    className={'form-control forminput'}
                    placeholder={'Phone Number'}
                  ></input>
                </div>
                <div
                  style={{
                    blockSize: '86px',
                    borderBlockEndColor: 'rgb(33, 37, 41)',
                    borderBlockStartColor: 'rgb(33, 37, 41)',
                    borderBottomColor: 'rgb(33, 37, 41)',
                    borderInlineEndColor: 'rgb(33, 37, 41)',
                    borderInlineStartColor: 'rgb(33, 37, 41)',
                    borderLeftColor: 'rgb(33, 37, 41)',
                    borderRightColor: 'rgb(33, 37, 41)',
                    borderTopColor: 'rgb(33, 37, 41)',
                    boxSizing: 'border-box',
                    caretColor: 'rgb(33, 37, 41)',
                    color: 'rgb(33, 37, 41)',
                    columnRuleColor: 'rgb(33, 37, 41)',
                    fontFamily: 'Manrope',
                    fontSize: '16px',
                    inlineSize: '600.875px',
                    lineHeight: '24px',
                    marginBlockEnd: '16px',
                    marginBottom: '1rem !important',
                    marginLeft: 0,
                    marginRight: 0,
                    outlineColor: 'rgb(33, 37, 41)',
                    textDecoration: 'none solid rgb(33, 37, 41)',
                    textDecorationColor: 'rgb(33, 37, 41)',
                    textEmphasisColor: 'rgb(33, 37, 41)',
                    textSizeAdjust: '100%',
                    WebkitTapHighlightColor: 'rgba(0, 0, 0, 0)',
                    WebkitTextFillColor: 'rgb(33, 37, 41)',
                    WebkitTextStrokeColor: 'rgb(33, 37, 41)',
                  }}
                  className={'mb-3'}
                >
                  <textarea
                    style={{
                      appearance: 'none',
                      backgroundClip: 'padding-box',
                      backgroundColor: 'rgba(0, 0, 0, 0)',
                      blockSize: '86px',
                      borderBlockEndColor: 'rgb(206, 212, 218)',
                      borderBlockStartColor: 'rgb(206, 212, 218)',
                      borderBottomColor: 'rgb(206, 212, 218)',
                      borderInlineEndColor: 'rgb(206, 212, 218)',
                      borderInlineStartColor: 'rgb(206, 212, 218)',
                      borderLeftColor: 'rgb(206, 212, 218)',
                      borderRightColor: 'rgb(206, 212, 218)',
                      borderTopColor: 'rgb(206, 212, 218)',
                      boxSizing: 'border-box',
                      caretColor: 'rgb(255, 255, 255)',
                      color: 'rgb(255, 255, 255)',
                      columnRuleColor: 'rgb(255, 255, 255)',
                      display: 'block',
                      fontFamily: 'Manrope',
                      fontSize: '16px',
                      inlineSize: '600.875px',
                      lineHeight: '24px',
                      marginLeft: 0,
                      marginRight: 0,
                      minBlockSize: '38px',
                      minHeight: '38px',
                      outlineColor: 'rgb(255, 255, 255)',
                      paddingBlockEnd: '6px',
                      paddingBlockStart: '6px',
                      paddingBottom: '6px',
                      paddingInlineEnd: '12px',
                      paddingInlineStart: '12px',
                      paddingLeft: '12px',
                      paddingRight: '12px',
                      paddingTop: '6px',
                      resize: 'vertical',
                      textDecoration: 'none solid rgb(255, 255, 255)',
                      textDecorationColor: 'rgb(255, 255, 255)',
                      textEmphasisColor: 'rgb(255, 255, 255)',
                      textSizeAdjust: '100%',
                      transitionDelay: '0s, 0s',
                      transitionDuration: '0.15s, 0.15s',
                      transitionProperty: 'border-color, box-shadow',
                      transitionTimingFunction: 'ease-in-out, ease-in-out',
                      WebkitTapHighlightColor: 'rgba(0, 0, 0, 0)',
                      WebkitTextFillColor: 'rgb(255, 255, 255)',
                      WebkitTextStrokeColor: 'rgb(255, 255, 255)',
                      width: '100%',
                    }}
                    className={'form-control formtext'}
                    rows={3}
                    placeholder={'Message'}
                  ></textarea>
                </div>
                <button
                  style={{
                    appearance: 'button',
                    backgroundColor: '#ff5733',
                    blockSize: '46px',
                    borderBlockEndColor: 'rgb(255, 255, 255)',
                    borderBlockEndStyle: 'none',
                    borderBlockEndWidth: '0px',
                    borderBlockStartColor: 'rgb(255, 255, 255)',
                    borderBlockStartStyle: 'none',
                    borderBlockStartWidth: '0px',
                    borderBottomColor: 'rgb(255, 255, 255)',
                    borderBottomStyle: 'none',
                    borderBottomWidth: '0px',
                    borderInlineEndColor: 'rgb(255, 255, 255)',
                    borderInlineEndStyle: 'none',
                    borderInlineEndWidth: '0px',
                    borderInlineStartColor: 'rgb(255, 255, 255)',
                    borderInlineStartStyle: 'none',
                    borderInlineStartWidth: '0px',
                    borderLeftColor: 'rgb(255, 255, 255)',
                    borderLeftStyle: 'none',
                    borderLeftWidth: '0px',
                    borderRightColor: 'rgb(255, 255, 255)',
                    borderRightStyle: 'none',
                    borderRightWidth: '0px',
                    borderTopColor: 'rgb(255, 255, 255)',
                    borderTopStyle: 'none',
                    borderTopWidth: '0px',
                    boxSizing: 'border-box',
                    caretColor: 'rgb(255, 255, 255)',
                    color: 'rgb(255, 255, 255)',
                    columnRuleColor: 'rgb(255, 255, 255)',
                    cursor: 'pointer',
                    fontFamily: 'Manrope',
                    fontSize: '16px',
                    inlineSize: '122.688px',
                    lineHeight: '24px',
                    marginLeft: 0,
                    marginRight: 0,
                    outlineColor: 'rgb(255, 255, 255)',
                    paddingBlockEnd: '11px',
                    paddingBlockStart: '11px',
                    paddingBottom: '11px',
                    paddingInlineEnd: '41px',
                    paddingInlineStart: '41px',
                    paddingLeft: '41px',
                    paddingRight: '41px',
                    paddingTop: '11px',
                    textDecoration: 'none solid rgb(255, 255, 255)',
                    textDecorationColor: 'rgb(255, 255, 255)',
                    textEmphasisColor: 'rgb(255, 255, 255)',
                    textSizeAdjust: '100%',
                    WebkitTapHighlightColor: 'rgba(0, 0, 0, 0)',
                    WebkitTextFillColor: 'rgb(255, 255, 255)',
                    WebkitTextStrokeColor: 'rgb(255, 255, 255)',
                  }}
                  type={'submit'}
                  className={'sendbtn enquiry-send'}
                >
                  SEND
                </button>
                <div
                  style={{
                    blockSize: '0px',
                    borderBlockEndColor: 'rgb(33, 37, 41)',
                    borderBlockStartColor: 'rgb(33, 37, 41)',
                    borderBottomColor: 'rgb(33, 37, 41)',
                    borderInlineEndColor: 'rgb(33, 37, 41)',
                    borderInlineStartColor: 'rgb(33, 37, 41)',
                    borderLeftColor: 'rgb(33, 37, 41)',
                    borderRightColor: 'rgb(33, 37, 41)',
                    borderTopColor: 'rgb(33, 37, 41)',
                    boxSizing: 'border-box',
                    caretColor: 'rgb(33, 37, 41)',
                    color: 'rgb(33, 37, 41)',
                    columnRuleColor: 'rgb(33, 37, 41)',
                    fontFamily: 'Manrope',
                    fontSize: '16px',
                    inlineSize: '600.875px',
                    lineHeight: '24px',
                    marginLeft: 0,
                    marginRight: 0,
                    outlineColor: 'rgb(33, 37, 41)',
                    textDecoration: 'none solid rgb(33, 37, 41)',
                    textDecorationColor: 'rgb(33, 37, 41)',
                    textEmphasisColor: 'rgb(33, 37, 41)',
                    textSizeAdjust: '100%',
                    WebkitTapHighlightColor: 'rgba(0, 0, 0, 0)',
                    WebkitTextFillColor: 'rgb(33, 37, 41)',
                    WebkitTextStrokeColor: 'rgb(33, 37, 41)',
                    height: '0px',
                  }}
                  className={'message-container'}
                ></div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Enquirenow;
